<<<<<<< HEAD
replicaCount: 1
=======
replicaCount: 2
>>>>>>> 09ea95e0cb48bdd1324584df4e9c53820ee718c9

image:
  repository: nginx
  tag: "1.27.3"
  pullPolicy: IfNotPresent

service:
  name: nginx-service
  type: ClusterIP
  port: 80
  targetPort: 9000

env:
  name: dev
